require("signal.battery")
require("signal.bright")
-- require("signal.volume")
require("signal.wifi")
require("signal.bluetooth")
require("signal.ram")
require("signal.cpu")
require("signal.volume")
require("signal.disk")
require("signal.dnd")
require("layout.popups.window_switcher").enable()
require("signal.uptime")
