require("layout.bar")
-- require("layout.controlCenter")
-- require("layout.dashboard")
-- require("layout.decorations")
require("layout.notify")
require("layout.ding")
require("layout.launcher")
require("layout.popups")
require("layout.menu")
require("layout.lockscreen")
require("layout.exitscreen")
require("layout.mainframe")
require("layout.moment")
